export const productsArray = [
  {
    id: 1,
    title: 'Midnight blue dress',
    price: 20,
    increaseAmount: 20,
    source: require('../images/img2.png'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#00008b'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#00008b',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Women'],
  },
  {
    id: 2,
    title: 'Champagne pink dress',
    price: 40,
    increaseAmount: 40,
    source: require('../images/img3.png'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla non diam phasellus vestibulum lorem sed risus ultriciestristique nulla non diam phasellus vestibulum lorem sed risus ultriciestristique nulla non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#f1bf9b'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#f1bf9b',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Women'],
  },
  {
    id: 3,
    title: 'Burgundy Rose dress',
    price: 20,
    increaseAmount: 20,
    source: require('../images/img4.png'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#e75480'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#e75480',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Women'],
  },
  {
    id: 4,
    title: 'Hunter green dress',
    price: 10,
    increaseAmount: 10,
    source: require('../images/img5.png'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#006400'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'teal'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#006400',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Women'],
  },
  {
    id: 5,
    title: 'Goldenrod dress',
    price: 30,
    increaseAmount: 30,
    source: require('../images/img6.png'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#ffd700'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#ffd700',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Women'],
  },
  {
    id: 6,
    title: 'Red dress',
    price: 45,
    increaseAmount: 45,
    source: require('../images/img7.png'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: 'red'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: 'red',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Women'],
  },
  {
    id: 7,
    title: 'Mint green dress',
    price: 50,
    increaseAmount: 50,
    source: require('../images/img8.png'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#8fed8f'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'teal'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#8fed8f',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Women'],
  },
  {
    id: 8,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../images/img9.png'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Women'],
  },
  //
  {
    id: 9,
    title: 'Midnight blue dress',
    price: 20,
    increaseAmount: 20,
    source: require('../newCollectionImg/bag-1.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#00008b'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#00008b',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Woman', 'Bags'],
  },
  {
    id: 10,
    title: 'Champagne pink dress',
    price: 40,
    increaseAmount: 40,
    source: require('../newCollectionImg/bag-2.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla non diam phasellus vestibulum lorem sed risus ultriciestristique nulla non diam phasellus vestibulum lorem sed risus ultriciestristique nulla non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#f1bf9b'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#f1bf9b',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Women', 'Bags'],
  },
  {
    id: 11,
    title: 'Burgundy Rose dress',
    price: 20,
    increaseAmount: 20,
    source: require('../newCollectionImg/bag-3.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#e75480'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#e75480',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Man', 'Hats'],
  },
  {
    id: 12,
    title: 'Hunter green dress',
    price: 10,
    increaseAmount: 10,
    source: require('../newCollectionImg/hat-1.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#006400'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'teal'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#006400',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Man', 'Hats'],
  },
  {
    id: 13,
    title: 'Goldenrod dress',
    price: 30,
    increaseAmount: 30,
    source: require('../newCollectionImg/hat-2.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#ffd700'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#ffd700',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Man', 'Hats'],
  },
  {
    id: 14,
    title: 'Red dress',
    price: 45,
    increaseAmount: 45,
    source: require('../newCollectionImg/shoe-1.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: 'red'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: 'red',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Man', 'Shoes'],
  },
  {
    id: 15,
    title: 'Mint green dress',
    price: 50,
    increaseAmount: 50,
    source: require('../newCollectionImg/shoe-2.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#8fed8f'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'teal'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#8fed8f',
    chosenSize: 'S',
    stock: 5,
    quantity: 1,
    category: ['All', 'Man', 'Shoes'],
  },
  {
    id: 16,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/shoe-3.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Man', 'Shoes'],
  },
  {
    id: 17,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/top-1.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Man', 'Tops'],
  },
  {
    id: 18,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/top-2.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Man', 'Tops'],
  },
  {
    id: 19,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/top-3.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Man', 'Tops'],
  },
  {
    id: 20,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/top-4.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Woman', 'Tops'],
  },
  {
    id: 21,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/top-5.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Woman', 'Tops'],
  },
  {
    id: 22,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/top-6.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Woman', 'Tops'],
  },
  {
    id: 23,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/trouser-1.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Woman', 'Trousers'],
  },
  {
    id: 24,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/trouser-2.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Woman', 'Trousers'],
  },
  {
    id: 25,
    title: 'Azure dress',
    price: 70,
    increaseAmount: 70,
    source: require('../newCollectionImg/trouser-3.jpg'),
    favorite: false,
    addedToCart: false,
    description:
      'non diam phasellus vestibulum lorem sed risus ultriciestristique nulla',

    colors: [
      {id: 1, color: '#87ceeb'},
      {id: 2, color: 'grey'},
      {id: 3, color: 'black'},
      {id: 4, color: 'green'},
    ],
    sizes: [
      {id: 1, size: 'S'},
      {id: 2, size: 'M'},
      {id: 3, size: 'L'},
      {id: 4, size: 'XL'},
    ],
    chosenColor: '#87ceeb',
    chosenSize: 'S',
    stock: 4,
    quantity: 1,
    category: ['All', 'Man', 'Trousers'],
  },
  //
];
